### ISSUE TITLE
crossOrigin error

### ISSUE THREAD

**Issue by ArnieD** [Gegelascience/ngx-view360#3]
When I tried to load an image from another server (API), I get the following error:

Failed to execute 'texImage2D' on 'WebGLRenderingContext': The ImageBitmap contains cross-origin data, and may not be loaded.

The domain is the same, site is running on www.xxx.com and the api on api.xxx.com

Can you make it possible to load an image from another server/url.

**Comment by Gegelascience** [comment]
Thank you for opening this issue, the CORS bug is fixed with the  1.3.1 version release.
Can you test it ?

**Comment by Gegelascience** [comment]
The bug has been fixed. I close this issue.
